<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class AchievementSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = Carbon::now();
        
        $achievements = [
            // First Steps (Bronze - Getting Started)
            [
                'key' => 'first_profile_complete',
                'name' => 'Profile Pioneer',
                'description' => 'Complete your photographer profile with bio and photo',
                'icon' => '👤',
                'badge_color' => 'bronze',
                'required_count' => 1,
                'points' => 50,
                'category' => 'portfolio',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'first_album',
                'name' => 'First Gallery',
                'description' => 'Upload your first album to showcase your work',
                'icon' => '📸',
                'badge_color' => 'bronze',
                'required_count' => 1,
                'points' => 50,
                'category' => 'portfolio',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'first_package',
                'name' => 'Package Creator',
                'description' => 'Create your first photography package',
                'icon' => '📦',
                'badge_color' => 'bronze',
                'required_count' => 1,
                'points' => 50,
                'category' => 'portfolio',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Booking Achievements (Silver to Platinum)
            [
                'key' => 'first_booking',
                'name' => 'First Client',
                'description' => 'Receive your first booking! The start of something great.',
                'icon' => '🎯',
                'badge_color' => 'silver',
                'required_count' => 1,
                'points' => 100,
                'category' => 'bookings',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'booking_milestone_10',
                'name' => 'Rising Star',
                'description' => 'Complete 10 bookings and establish your presence',
                'icon' => '⭐',
                'badge_color' => 'gold',
                'required_count' => 10,
                'points' => 300,
                'category' => 'bookings',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'booking_milestone_50',
                'name' => 'Professional',
                'description' => 'Reach 50 bookings and prove your expertise',
                'icon' => '🏆',
                'badge_color' => 'gold',
                'required_count' => 50,
                'points' => 1000,
                'category' => 'bookings',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'booking_milestone_100',
                'name' => 'Elite Photographer',
                'description' => '100 bookings! You are among the platform elite.',
                'icon' => '👑',
                'badge_color' => 'platinum',
                'required_count' => 100,
                'points' => 2500,
                'category' => 'bookings',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Review Achievements (Quality Focus)
            [
                'key' => 'first_five_star',
                'name' => 'Five Star Debut',
                'description' => 'Receive your first 5-star review',
                'icon' => '⭐',
                'badge_color' => 'silver',
                'required_count' => 1,
                'points' => 100,
                'category' => 'reviews',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'five_star_streak_10',
                'name' => 'Consistent Excellence',
                'description' => 'Earn 10 five-star reviews',
                'icon' => '🌟',
                'badge_color' => 'gold',
                'required_count' => 10,
                'points' => 500,
                'category' => 'reviews',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'perfect_score',
                'name' => 'Perfection',
                'description' => 'Maintain a 5.0 average rating with 20+ reviews',
                'icon' => '💎',
                'badge_color' => 'platinum',
                'required_count' => 20,
                'points' => 1500,
                'category' => 'reviews',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Competition Achievements
            [
                'key' => 'first_competition',
                'name' => 'Competitor',
                'description' => 'Enter your first photography competition',
                'icon' => '🎪',
                'badge_color' => 'bronze',
                'required_count' => 1,
                'points' => 50,
                'category' => 'competitions',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'competition_winner',
                'name' => 'Winner',
                'description' => 'Win your first photography competition!',
                'icon' => '🏅',
                'badge_color' => 'gold',
                'required_count' => 1,
                'points' => 500,
                'category' => 'competitions',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'competition_champion',
                'name' => 'Champion',
                'description' => 'Win 3 photography competitions',
                'icon' => '🥇',
                'badge_color' => 'platinum',
                'required_count' => 3,
                'points' => 2000,
                'category' => 'competitions',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Portfolio Achievements
            [
                'key' => 'portfolio_master',
                'name' => 'Portfolio Master',
                'description' => 'Upload 30+ photos across multiple albums',
                'icon' => '🎨',
                'badge_color' => 'gold',
                'required_count' => 30,
                'points' => 400,
                'category' => 'portfolio',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'package_pro',
                'name' => 'Package Pro',
                'description' => 'Create 5+ diverse photography packages',
                'icon' => '📋',
                'badge_color' => 'gold',
                'required_count' => 5,
                'points' => 300,
                'category' => 'portfolio',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'complete_profile',
                'name' => 'Complete Profile',
                'description' => 'Achieve 100% profile completeness',
                'icon' => '✨',
                'badge_color' => 'gold',
                'required_count' => 100,
                'points' => 500,
                'category' => 'portfolio',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Growth & Popularity
            [
                'key' => 'profile_views_100',
                'name' => 'Getting Noticed',
                'description' => 'Reach 100 profile views',
                'icon' => '👀',
                'badge_color' => 'silver',
                'required_count' => 100,
                'points' => 100,
                'category' => 'community',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'profile_views_1000',
                'name' => 'Popular',
                'description' => 'Reach 1,000 profile views',
                'icon' => '🔥',
                'badge_color' => 'gold',
                'required_count' => 1000,
                'points' => 500,
                'category' => 'community',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'verified_photographer',
                'name' => 'Verified Photographer',
                'description' => 'Get verified status on the platform',
                'icon' => '✅',
                'badge_color' => 'platinum',
                'required_count' => 1,
                'points' => 1000,
                'category' => 'community',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Earnings Milestones
            [
                'key' => 'first_payment',
                'name' => 'First Earnings',
                'description' => 'Receive your first payment through the platform',
                'icon' => '💰',
                'badge_color' => 'silver',
                'required_count' => 1,
                'points' => 200,
                'category' => 'bookings',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'earnings_10k',
                'name' => 'Money Maker',
                'description' => 'Earn ৳10,000 through platform bookings',
                'icon' => '💵',
                'badge_color' => 'gold',
                'required_count' => 10000,
                'points' => 800,
                'category' => 'bookings',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'earnings_100k',
                'name' => 'High Earner',
                'description' => 'Earn ৳100,000 through platform bookings',
                'icon' => '💎',
                'badge_color' => 'platinum',
                'required_count' => 100000,
                'points' => 3000,
                'category' => 'bookings',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],

            // Community & Engagement
            [
                'key' => 'event_participant',
                'name' => 'Event Participant',
                'description' => 'Attend your first photography event',
                'icon' => '🎉',
                'badge_color' => 'bronze',
                'required_count' => 1,
                'points' => 50,
                'category' => 'community',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'fast_responder',
                'name' => 'Fast Responder',
                'description' => 'Maintain an average response time under 2 hours',
                'icon' => '⚡',
                'badge_color' => 'gold',
                'required_count' => 1,
                'points' => 300,
                'category' => 'community',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
            [
                'key' => 'repeat_clients',
                'name' => 'Client Favorite',
                'description' => 'Have 5 clients book you more than once',
                'icon' => '❤️',
                'badge_color' => 'platinum',
                'required_count' => 5,
                'points' => 1500,
                'category' => 'bookings',
                'is_active' => true,
                'created_at' => $now,
                'updated_at' => $now,
            ],
        ];

        DB::table('achievements')->insert($achievements);
    }
}
