<?php

namespace App\Services;

use App\Models\Certificate;
use App\Models\CertificateTemplate;
use App\Models\Competition;
use App\Models\Event;
use App\Models\User;
use Illuminate\Support\Carbon;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class CertificateIssuanceService
{
    public function __construct(protected CertificateGenerator $generator)
    {
    }

    public function issueCertificate(
        CertificateTemplate $template,
        ?Event $event = null,
        ?Competition $competition = null,
        ?User $user = null,
        ?string $recipientName = null,
        ?string $participantEmail = null,
        ?string $issueDate = null,
        ?string $notes = null,
        ?string $sourceType = null,
        ?int $sourceId = null,
        bool $generateFile = true,
        bool $autoGenerated = false
    ): Certificate {
        if (!$user && empty($recipientName)) {
            throw new \InvalidArgumentException('Either user or recipient name must be provided.');
        }

        $resolvedName = $recipientName ?: ($user?->full_name ?: $user?->name);
        $resolvedEmail = $participantEmail ?: $user?->email;
        $resolvedIssuedAt = $issueDate ? Carbon::parse($issueDate) : now();

        $existingQuery = Certificate::query()
            ->where('template_id', $template->id)
            ->where('status', 'issued')
            ->where('event_id', $event?->id)
            ->where('competition_id', $competition?->id);

        if ($user) {
            $existingQuery->where(function ($query) use ($user) {
                $query->where('user_id', $user->id)
                    ->orWhere('issued_to_user_id', $user->id);
            });
        } else {
            $existingQuery->where(function ($query) use ($resolvedName) {
                $query->where('recipient_name', $resolvedName)
                    ->orWhere('issued_to_name', $resolvedName);
            });
        }

        $existing = $existingQuery->first();

        if ($existing) {
            return $existing;
        }

        return DB::transaction(function () use (
            $template,
            $event,
            $competition,
            $user,
            $resolvedName,
            $resolvedEmail,
            $resolvedIssuedAt,
            $notes,
            $sourceType,
            $sourceId,
            $generateFile,
            $autoGenerated
        ) {
            $resolvedSourceType = $sourceType ?: ($competition
                ? 'competition'
                : (($event?->event_type === 'workshop' || $event?->type === 'workshop') ? 'workshop' : 'event'));
            $resolvedSourceId = $sourceId ?: ($competition?->id ?? $event?->id);

            $certificate = Certificate::create([
                'certificate_code' => $this->generator->generateCode(),
                'template_id' => $template->id,
                'event_id' => $event?->id,
                'competition_id' => $competition?->id,
                'source_type' => $resolvedSourceType,
                'source_id' => $resolvedSourceId,
                'user_id' => $user?->id,
                'issued_to_user_id' => $user?->id,
                'recipient_name' => $resolvedName,
                'issued_to_name' => $resolvedName,
                'issued_to_email' => $resolvedEmail,
                'issued_at' => $resolvedIssuedAt,
                'issue_date' => $resolvedIssuedAt,
                'issued_by_user_id' => Auth::id(),
                'created_by_user_id' => Auth::id() ?? 1,
                'notes' => $notes,
                'status' => 'issued',
            ]);

            $certificate->logs()->create([
                'user_id' => Auth::id(),
                'action_type' => $autoGenerated ? 'auto_issued' : 'manual_issued',
                'entity_type' => 'certificate',
                'entity_id' => $certificate->id,
                'message' => 'Certificate issued successfully',
                'metadata' => [
                    'template' => $template->title,
                    'event' => $event?->title,
                    'competition' => $competition?->title ?? $competition?->name,
                    'source_type' => $resolvedSourceType,
                    'source_id' => $resolvedSourceId,
                ],
            ]);

            if ($generateFile) {
                $this->generator->generateCertificate($certificate);
            }

            return $certificate->fresh(['template', 'event', 'competition', 'user']);
        });
    }

    public function issueCertificateBulk(
        CertificateTemplate $template,
        ?Event $event,
        ?Competition $competition,
        array $participants,
        bool $generateFile = true,
        bool $autoGenerated = false
    ): Collection {
        $certificates = collect();

        foreach ($participants as $participant) {
            try {
                $cert = $this->issueCertificate(
                    $template,
                    $event,
                    $competition,
                    $participant['user'] ?? null,
                    $participant['name'] ?? null,
                    $participant['email'] ?? null,
                    $participant['issued_at'] ?? null,
                    $participant['notes'] ?? null,
                    $participant['source_type'] ?? null,
                    $participant['source_id'] ?? null,
                    $generateFile,
                    $autoGenerated
                );
                $certificates->push($cert);
            } catch (\Throwable $e) {
                Log::error('Failed to issue certificate', [
                    'participant' => $participant,
                    'error' => $e->getMessage(),
                ]);
            }
        }

        return $certificates;
    }

    public function autoIssueCertificatesForEvent(Event $event, CertificateTemplate $template): Collection
    {
        $attendees = $event->registrations()
            ->whereNotNull('attended_at')
            ->with('user')
            ->get();

        $participants = $attendees->map(function ($attendance) {
            return [
                'user' => $attendance->user,
                'name' => $attendance->user->full_name ?? $attendance->user->name,
                'email' => $attendance->user->email,
                'issued_at' => now()->toDateTimeString(),
            ];
        })->toArray();

        return $this->issueCertificateBulk($template, $event, null, $participants, generateFile: true, autoGenerated: true);
    }

    public function autoIssueCertificatesForCompetition(Competition $competition, CertificateTemplate $template): Collection
    {
        $submissions = $competition->submissions()
            ->where(function ($query) {
                $query->where('is_winner', true)->orWhereNotNull('award_type');
            })
            ->with('photographer')
            ->get();

        $participants = $submissions->map(function ($submission) {
            return [
                'user' => $submission->photographer,
                'name' => $submission->photographer?->full_name ?? $submission->photographer?->name,
                'email' => $submission->photographer?->email,
                'issued_at' => now()->toDateTimeString(),
            ];
        })->toArray();

        return $this->issueCertificateBulk($template, null, $competition, $participants, generateFile: true, autoGenerated: true);
    }

    public function revokeCertificate(Certificate $certificate, ?string $reason = null): Certificate
    {
        $certificate->update([
            'status' => 'revoked',
            'revoked_at' => now(),
            'revoked_by_user_id' => Auth::id(),
        ]);

        $certificate->logs()->create([
            'user_id' => Auth::id(),
            'action_type' => 'revoked',
            'entity_type' => 'certificate',
            'entity_id' => $certificate->id,
            'message' => 'Certificate revoked',
            'metadata' => ['reason' => $reason],
        ]);

        return $certificate;
    }

    public function reissueCertificate(Certificate $certificate): Certificate
    {
        if (!$certificate->isRevoked()) {
            throw new \RuntimeException('Cannot reissue a certificate that is not revoked');
        }

        $certificate->update([
            'status' => 'issued',
            'revoked_at' => null,
            'revoked_by_user_id' => null,
        ]);

        $certificate->logs()->create([
            'user_id' => Auth::id(),
            'action_type' => 'reissued',
            'entity_type' => 'certificate',
            'entity_id' => $certificate->id,
            'message' => 'Certificate reissued',
        ]);

        return $certificate;
    }

    public function downloadCertificate(Certificate $certificate)
    {
        if (!$certificate->file_path) {
            throw new \RuntimeException('Certificate file not generated yet');
        }

        $certificate->logs()->create([
            'user_id' => Auth::id(),
            'action_type' => 'downloaded',
            'entity_type' => 'certificate',
            'entity_id' => $certificate->id,
            'message' => 'Certificate downloaded',
        ]);

        return $certificate->file_path;
    }
}
