<?php

namespace App\Services;

use App\Jobs\GenerateCertificateAssetsJob;
use App\Models\CertificateAutomationRule;
use App\Models\Competition;
use App\Models\Event;
use App\Models\User;
use Illuminate\Support\Collection;

class CertificateAutomationService
{
    public function issueForEventAttendance(Event $event, User $user): ?int
    {
        $rule = CertificateAutomationRule::query()
            ->active()
            ->where('trigger_type', 'event_attendance')
            ->where(function ($query) use ($event) {
                $query->whereNull('source_id')
                    ->orWhere(function ($subQuery) use ($event) {
                        $subQuery->where('source_type', 'event')->where('source_id', $event->id);
                    })
                    ->orWhere(function ($subQuery) use ($event) {
                        $subQuery->where('source_type', 'workshop')->where('source_id', $event->id);
                    });
            })
            ->with('template')
            ->first();

        if (!$rule || !$rule->template) {
            return null;
        }

        $issuanceService = app(CertificateIssuanceService::class);
        $certificate = $issuanceService->issueCertificate(
            template: $rule->template,
            event: $event,
            competition: null,
            user: $user,
            recipientName: null,
            participantEmail: null,
            issueDate: now()->toDateTimeString(),
            notes: 'Automatically issued via event attendance automation rule',
            generateFile: false,
            autoGenerated: true,
        );

        GenerateCertificateAssetsJob::dispatch($certificate->id)->onQueue('certificates');

        return $certificate->id;
    }

    public function issueForCompetitionWinners(Competition $competition): Collection
    {
        $rule = CertificateAutomationRule::query()
            ->active()
            ->where('trigger_type', 'competition_winners_announced')
            ->where(function ($query) use ($competition) {
                $query->whereNull('source_id')
                    ->orWhere(function ($subQuery) use ($competition) {
                        $subQuery->where('source_type', 'competition')->where('source_id', $competition->id);
                    });
            })
            ->with('template')
            ->first();

        if (!$rule || !$rule->template) {
            return collect();
        }

        $issuanceService = app(CertificateIssuanceService::class);
        $certificates = $issuanceService->autoIssueCertificatesForCompetition($competition, $rule->template);

        $certificates->each(function ($certificate) {
            GenerateCertificateAssetsJob::dispatch($certificate->id)->onQueue('certificates');
        });

        return $certificates;
    }
}
